Almost complete two issues i cannot resolve
Hoobachube/jacks-app-chest pull request #22
Opened 2020-05-30 12:37 UTC by Hoobachube

1st draft almost complete. I have used my current c.v as the template.  Obviously I will edit it to a more useful c.v to do with coding when the time arises I cannot seem to format this so there must be some error that vscode cannot deal with but I cant find it.  Also I have Bullet points that should not be there in the cover supervisor section that i cant remove.

2020-05-31 20:03 UTC, alexw1983 requested changes

2020-05-31 20:03 UTC, alexw1983 commented on cv.html
> +    <b><i>Areas of Expertise include:</i></B>
Avoid `<b>` and `<i>` tags if a more descriptive tag is available

2020-05-31 20:03 UTC, alexw1983 commented on cv.html
> +  <table class="table table-borderless">
Three columns can confuse people stick to one column for articles.

2020-05-31 20:03 UTC, alexw1983 commented on cv.html
> +  <h3 style="text-align: center;">FERNDALE FOODS</h3>
don't use inline styles

2020-05-31 20:03 UTC, alexw1983 commented on cv.html
> +  <b>Key Accomplishments:</b>
is this a heading or a bold bit of text

2020-06-08 12:22 UTC, Hoobachube commented
I must be trying to implement the style sheet incorrectly.  I tried the remove text-align attribute to a style sheet but didn't work

2020-06-17 14:07 UTC, Hoobachube commented
I have added the blog style in the about me page.  I aim to remove the c.v page completely but wanted to leave it for the moment to help me hone my css skills before removing.  Hope this was alright

2020-08-02 20:58 UTC, closed without merging